# Generated by Django 4.0.4 on 2022-05-22 08:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_person_name', models.CharField(max_length=1000)),
                ('booking_person_address', models.TextField(max_length=20000)),
                ('booking_person_mobile', models.CharField(max_length=1000)),
                ('booking_date_time', models.DateTimeField(default=datetime.datetime(2022, 5, 22, 14, 3, 49, 280453))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
