# Generated by Django 4.0.4 on 2022-05-22 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookingApp', '0002_alter_bookingmodel_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ServiceApp.servicemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 14, 9, 25, 235322)),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
