# Generated by Django 4.0.4 on 2022-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=1000)),
                ('service_description', models.TextField(max_length=10000)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
